---
- name: Install sysbench script
  hosts: all
  remote_user: root
  vars:
      sysbench_script_dir: "/home/sysbench"
  tasks:
     - name: Install sysbench script
       file: path={{ sysbench_script_dir }} state=directory

     - name: Install sysbench script
       template:
        src: "script/{{ item }}"
        dest: "{{ sysbench_script_dir }}/{{ item }}"
        mode: 0755
       with_items:
        - sysbench_cpu.sh
        - sysbench_fileio.sh
        - sysbench_mysql_oltp.sh

