---
- name: Install MySQL servers
  hosts: mha-node
  remote_user: root
  vars_files:
    - ../../common/mysql/defaults/main.yml
    - var/main.yml
  roles:
    - mysql
    - slave
    - mha4mysql-node

- name: Install mha4mysql-manager
  hosts: mha-manager
  remote_user: root
  vars_files:
  - ../../common/mysql/defaults/main.yml
  - var/main.yml
  roles:
    - mha4mysql-manager

- name: Install binlog server
  hosts: binlog-server
  remote_user: root
  vars_files:
  - ../../common/mysql/defaults/main.yml
  - var/main.yml
  roles:
    - binlogserver