---
- name: mydumper | Copy file
  copy: src={{ software_files_path }}/{{ mydumper_package }} dest=/tmp/{{ mydumper_package }}

- name: mydumper | Install mydumper
  command: "yum -y localinstall /tmp/{{ mydumper_package }}"
