---
 - name: tpcc-mysql | Install tpcc-mysql via src
   shell: "{{ item }} chdir=/usr/local/src"
   with_items:
    - "git clone https://github.com/Percona-Lab/tpcc-mysql.git"
    - "cd tpcc-mysql/src && make"
    - "ln -s /usr/local/src/tpcc-mysql/tpcc_load /bin/tpcc_load"
    - "ln -s /usr/local/src/tpcc-mysql/tpcc_start /bin/tpcc_start"
