---
- name: Initialize | Create inception directory owner.
  file: path={{ item }} recurse=yes
  with_items:
     - /var/log/inception
     - /etc/inception

- name: Initialize | Create configuration file inc.cnf.
  template:
    src: ../templates/inc.cnf
    dest: /etc/inception/inc.cnf

- name: Initialize | start inception
  shell: nohup Inception --defaults-file=/etc/inception/inc.cnf &

- name: Initialize | Wait for inception start.
  wait_for: port=6669 delay=1 timeout=15
