---
- name: Transfer create user sql to remote host
  template:
    src: ../templates/create_monitor_user.sql
    dest: /tmp/create_monitor_user.sql

- name: Create monitor user on master
  shell: mysql -hlocalhost -uroot -p{{ mysql_password }} -S {{ mysql_sock }} < /tmp/create_monitor_user.sql

- name: Clear temp file tmp/create_monitor_user.sql
  file:
    dest: tmp/create_monitor_user.sql
    state: absent

- name: Install keepalived
  yum:
    name: keepalived
    state: present

- name: Transfer keepalived.conf to remote host
  template:
    src: ../templates/keepalived.conf
    dest: /etc/keepalived/keepalived.conf

- name: Transfer checkMySQL.py to remote host
  template:
    src: ../templates/checkMySQL.py.j2
    dest: /etc/keepalived/checkMySQL.py
    mode: 755