---
install_method: "src"

software_files_path: "/downloads"
software_install_path: "/usr/local"
software_install_src_path: "/usr/local/src"

zabbix_server_package: "zabbix-3.4.14.tar.gz"
zabbix_server_install_dir: "{{ software_install_path }}/zabbix"

startup_on_boot: True
read_only: 0

zabbix_server_source_configure_command: >
  ./configure
  --prefix={{ zabbix_server_install_dir }}
  --enable-server
  --enable-agent
  --with-mysql
  --with-net-snmp
  --with-libcurl
  --with-libxml2
  --with-ssh2


mysql_admin_user: admin
mysql_admin_pwd: aaaaaa

DBEngine: InnoDB
DBHost: 127.0.0.1
DBName: zabbix
DBUser: zabbix
DBPassword: zabbixx
DBPort: 3306