---
# MySQL Master-Master + Keepalived 安装
- name: Install MySQL with Master-Master Node1
  hosts: node1
  remote_user: root
  vars_files:
    - ../common/mysql/defaults/main.yml
    - var/main.yml

  roles:
    - mysql
    - slave

- name: Install MySQL with Master-Master Node2
  hosts: node2
  remote_user: root
  vars_files:
    - ../common/mysql/defaults/main.yml
    - var/main.yml

  roles:
    - mysql
    - slave

- name: Install keepalived
  hosts: all
  remote_user: root
  vars_files:
    - ../common/mysql/defaults/main.yml
    - var/main.yml

  roles:
    - keepalived