Vagrant.configure("2") do |config|

    (0..5).each do |i|

        config.vm.define "node#{i}" do |node|

			# 设置虚拟机的Box
			#node.vm.box = "bento/centos-6.7"
			node.vm.box = "bento/centos-7.2"

			# 设置虚拟机的主机名
			node.vm.hostname="node#{i}"

			# 设置虚拟机的IP
			node.vm.network "private_network", ip: "192.168.1.10#{i}"

			# 共享目录
			node.vm.synced_folder "D:/Work/PyCharm/", "/vagrant"
			node.vm.synced_folder "G:/CentOS Downloads", "/vagrant/downloads"

			# VirtaulBox相关配置
			node.vm.provider "virtualbox" do |v|

				# 设置虚拟机的名称
				v.name = "node#{i}"

				# 设置虚拟机的内存大小  
				v.memory = 256

				# 设置虚拟机的CPU个数
				v.cpus = 1
			end

        end
    end
end
