---
- name: Install redis master
  hosts: redis_master
  remote_user: root
  vars:
    - redis_master_host: '192.168.1.101'
    - redis_master_port: '8380'
  roles:
    - { role: redis, redis_port: 8380 }

- name: Install redis slave
  hosts: redis_slave
  remote_user: root
  vars:
    - redis_master_host: '192.168.1.101'
    - redis_master_port: '8380'
  roles:
    - { role: redis, redis_port: 8380, redis_slave: true }
