---
- name: Install MySQL servers
  hosts: pxc_node
  remote_user: root
  vars_files:
    - ../common/mysql/defaults/main.yml
    - var/main.yml
  roles:
    - mysql
    - xtrabackup
#    - percona-toolkit

- name: Install MySQL servers
  hosts: proxy_server
  remote_user: root
  vars_files:
    - var/main.yml
  roles:
    - proxysql