---
 - name: Install dev requirements
   yum: name={{ item }} state=present
   with_items:
    - "git"
    - "gcc"
    - "gcc-c++"
    - "make"
    - "cmake"
    - "automake"
    - "pkgconfig"
    - "libtool"