#mysql_version: "8.0.11"
#mysql_package: "mysql-8.0.11-linux-glibc2.12-x86_64.tar.gz"

mysql_version: "5.7.20"
mysql_package: "mysql-5.7.20-linux-glibc2.12-x86_64.tar.gz"
mysql_datahome: "/data/mgr"
mysql_basedir: "{{ software_install_path }}/mysql"

mysql_repl_user: repl
mysql_repl_password: repl@1234
mysql_port: 7706
mysql_password: aaaaaa

# 组复制
master_info_repository: "TABLE"
gtid: True
group_replication: True
mysql_plugins:
 - { name: "group_replication", so: "group_replication.so" }

# group_name 可通过select uuid()  或 shell uuidgen 生成
group_replication_group_name : '7cd80e42-3308-11e8-a596-0800275ae9e7'
group_seed_port: 33081