---
- name: Transfer sql to remote host
  template:
    src: ../templates/password.sql
    dest: /tmp/password.sql

- name: reset root password
  shell: mysql -uroot -S {{ mysql_sock }} < /tmp/password.sql

- name: clear temp file tmp/password.sql
  file:
    dest: tmp/password.sql
    state: absent