---
# 设置帐号密码,安装插件
- name: Initialize | Transfer sql to remote host
  template:
    src: ../templates/setup.sql
    dest: /tmp/setup.sql

- name: Initialize | reset root password
  shell: "{{ mysql_basedir }} -uroot -S {{ mysql_sock }} < /tmp/setup.sql"

- name: Initialize | clear temp file tmp/setup.sql
  file:
    dest: tmp/setup.sql
    state: absent