---
# 创建帐号
# groupadd mysql
# useradd -g mysql -d /usr/local/mysql -s /sbin/nologin -M -n mysql
 - name: Install | Create mysql user
   user: name=mysql shell=/sbin/nologin home=/usr/local/mysql createhome=no state=present
 - name: Make dir /opt/mysql
   file: path=/opt/mysql state=directory owner=mysql group=mysql

# 由本地传输mysql安装包到目标主机、并把安装包解压到/opt/mysql
# 等价bash
# scp mysql-xxxx.tar.gz 192.168.xx.xx:/tmp/
#tar -xvf /tmp/mysq-xxxx.tar.gz -C /opt/mysql/
 - name: Install | Transfer MySQL install package to remote host and unarchive to /opt/mysql/
   unarchive:
    src: "{{ software_files_path }}/{{ mysql_package }}"
    dest: /opt/mysql
    owner: mysql
    group: mysql

#  mv /opt/mysql/mysql-5.7.20-linux-glibc2.12-x86_64 /opt/mysql/mysql-x.xx
 - name: Install | Rename MySQL package name to a short name
   command: mv /opt/mysql/{{ mysql_package | regex_replace('.tar.gz','') }}  /opt/mysql/{{ mysql_dirname }}

# 设置权限
# 等价bash
# chown -R mysql:mysql /usr/local/mysql-xxxx
 - name: Install | Change owner to MySQL user
   file:
    path: /opt/mysql/{{ mysql_dirname }}
    owner: mysql
    group: mysql
    recurse: yes

# 创建连接文件
# 等价bash
# ln -s /opt/mysql/mysql-xx.xx /usr/local/mysql
 - name: Install | Make link /opt/mysql/mysql-xx.yy.zz to /usr/local/mysql
   file:
    src: /opt/mysql/{{ mysql_dirname }}
    dest: /usr/local/mysql
    state: link
    owner: mysql
    group: mysql

#导出mysql的库文件
 - name: Install | Export MySQL share object (*.os)
   template:
    src: ../templates/mysql.conf
    dest: /etc/ld.so.conf.d/mysql.conf

#加载共享库
 - name: Install | Load share object
   shell: ldconfig

#导出PATH环境变量
 - name: Install | Export path env variable
   lineinfile:
    path: /etc/profile
    line: export PATH=/usr/local/mysql/bin/:$PATH
    insertafter: EOF

 - name: Install | Export path env to /root/.bashrc
   lineinfile:
    path: /root/.bashrc
    line: export PATH=/usr/local/mysql/bin/:$PATH
    insertafter: EOF
