---
- name: zabbix_server | Check if zabbix_server local file is already configured.
  stat: path={{ zabbix_server_install_dir }}
  register: install_result
- block:
  - import_tasks: install_dependents.yml
  - import_tasks: install_zabbix_server_using_{{ install_method }}.yml
  when: not install_result.stat.exists

- import_tasks: init_mysql.yml
- import_tasks: init_service.yml
