- name: sysbench | Check if sysbench src file is already installed.
  stat: path=/usr/local/src/sysbench
  register: sysbench_src_installed
  ignore_errors: True
- name: sysbench | Install sysbench via src
  import_tasks: install_sysbench_using_src.yml
  when: not sysbench_src_installed.stat.exists
