---
# author: lework

# Include OS-specific installation tasks.
- include: setup-RedHat.yml
  when: (ruby_install_from_source == false) and (ansible_os_family == 'RedHat')

- include: setup-Debian.yml
  when: (ruby_install_from_source == false) and (ansible_os_family == 'Debian')

# Install ruby from source when ruby_install_from_source is true.
- include: install-from-source.yml
  when: ruby_install_from_source == true

- name: Change ruby gem source.
  shell: "gem sources --add {{ ruby_gem_sources }} --remove http://rubygems.org/ && gem source --remove https://rubygems.org/"
  
# Install Bundler and configured gems.
- name: Install Bundler.
  gem: name=bundler state=present user_install=no
  when: ruby_install_bundler
  
- name: Change bundler source.
  shell: "bundle config mirror.https://rubygems.org {{ ruby_gem_sources }}"
  when: ruby_install_bundler
  
- name: Install configured gems.
  gem: "name={{ item }} state=present"
  become: yes
  become_user: "{{ ruby_install_gems_user }}"
  with_items: "{{ ruby_install_gems }}"
