---
- name: Install MySQL Master
  hosts: all
#  gather_facts: no
  remote_user: root
  vars_files:
    - ../../common/mysql/defaults/main.yml
    - var/main.yml
  roles:
    - { role: mysql}
    - { role: slave}