---
- name: Initialize MHA
  hosts: mha-manager
  remote_user: root
  vars:
    iface_name: enp0s8
  vars_files:
    - ../common/mysql/defaults/main.yml
    - var/main.yml

  tasks:
    - name: Initialize | Transfer script to manager host
      template:
        src: templates/scripts/{{ item }}
        dest: /usr/local/bin/{{ item }}
        mode: 0755
      with_items:
        - "master_ip_failover"
        - "master_ip_online_change"
        - "power_manager"
        - "send_report"

    - name: Initialize | Transfer cnf file to manager host
      template:
        src: templates/mha_app.cnf.j2
        dest: /etc/masterha/app1.cnf
